export const SAY_HELLO = 'SAY_HELLO'
export const SET_SCHEDULE_TYPE = 'SET_SCHEDULE_TYPE'
export const UPDATE_NEW_LOCATIONS = 'UPDATE_NEW_LOCATIONS'
export const REPLACE_SNAPSHOT = 'REPLACE_SNAPSHOT'
